### ISSUE TITLE
Unable to use shield-url for bosh create-env

### ISSUE THREAD

**Issue by lnguyen** [starkandwayne/shield-boshrelease#110]
When using shield-url and using `bosh create-env`, getting template unable to find agent.key
```
Stopping registry... Finished (00:00:00)
Cleaning up rendered CPI jobs... Finished (00:00:00)

Deploying:
 Building state for instance 'bosh/0':
   Rendering job templates for instance 'bosh/0':
     Rendering templates for job 'shield-agent/ad85475f3181f4853c70f5d9e01c4ad4ecc95b88':
       Rendering template src: bin/shield-agent, dst: bin/shield-agent:
         Rendering template src: /home/ubuntu/.bosh/installations/20d8b9a8-00ef-42f1-5a7e-ec6fbdf37628/tmp/bosh-release-job899931841/templates/bin/shield-agent, dst: /home/ubuntu/.bosh/installations/20d8b9a8-00ef-42f1-5a7e-ec6fbdf37628/tmp/rendered-jobs985293068/bin/shield-agent:
           Running ruby to render templates:
             Running command: 'ruby /home/ubuntu/.bosh/installations/20d8b9a8-00ef-42f1-5a7e-ec6fbdf37628/tmp/erb-renderer842246686/erb-render.rb /home/ubuntu/.bosh/installations/20d8b9a8-00ef-42f1-5a7e-ec6fbdf37628/tmp/erb-renderer842246686/erb-context.json /home/ubuntu/.bosh/installations/20d8b9a8-00ef-42f1-5a7e-ec6fbdf37628/tmp/bosh-release-job899931841/templates/bin/shield-agent /home/ubuntu/.bosh/installations/20d8b9a8-00ef-42f1-5a7e-ec6fbdf37628/tmp/rendered-jobs985293068/bin/shield-agent', stdout: '', stderr: '/home/ubuntu/.bosh/installations/20d8b9a8-00ef-42f1-5a7e-ec6fbdf37628/tmp/erb-renderer842246686/erb-render.rb:189:in `rescue in render': Error filling in template '/home/ubuntu/.bosh/installations/20d8b9a8-00ef-42f1-5a7e-ec6fbdf37628/tmp/bosh-release-job899931841/templates/bin/shield-agent' for shield-agent/0 (line 10: #<TemplateEvaluationContext::UnknownProperty: Can't find property 'agent.key'>) (RuntimeError)
    from /home/ubuntu/.bosh/installations/20d8b9a8-00ef-42f1-5a7e-ec6fbdf37628/tmp/erb-renderer842246686/erb-render.rb:175:in `render'
    from /home/ubuntu/.bosh/installations/20d8b9a8-00ef-42f1-5a7e-ec6fbdf37628/tmp/erb-renderer842246686/erb-render.rb:200:in `<main>'
':
               exit status 1

Exit code 1
```

**Comment by jhunt** [comment]
This is to be expected, since you need to set both `agent.key` and `shield-url`
